function [t, y] = ab3cn(explicitOdefun, implicitOdefun, t, y0, options)
    if nargin < 4
        options = struct('optimmethod', @(fun, x0) fsolve(fun, x0, ...
            optimoptions('fsolve', 'Display', 'off')));
    end

    n = length(t);
    y = zeros(length(y0),n);
    
    y(:, 1) = y0;
    y(:, 2) = y(:, 1) + ...
        (t(2) - t(1)) * explicitOdefun(t(1), y(:, 1));
    y(:, 2) = options.optimmethod(@(x) x - y(:, 2) - ...
        (t(2) - t(1)) * implicitOdefun(t(2), x), y(:, 1));
    y(:, 3) = y(:, 2) + ...
        (t(3) - t(2)) * explicitOdefun(t(2:-1:1), y(:, 2:-1:1)) * [3/2, -1/2]';
    y(:, 3) = options.optimmethod(@(x) x - y(:, 2) - ...
        (t(3) - t(2)) * implicitOdefun(t(3), x), y(:, 2));
    
    explicitCoeff = [23/12,-4/3,5/12]';
    implicitCoeff = [3/2,-1/2]';
    
    for i = 4:n
        dt = t(i) - t(i - 1);
        y(:, i) = y(:, i-1) + ...
            dt * [explicitOdefun(t(i-1), y(:, i-1)), ...
                explicitOdefun(t(i-2), y(:, i-2)), ...
                explicitOdefun(t(i-3), y(:, i-3))] *  explicitCoeff;
        y(:, i) = options.optimmethod(@(x) x - y(:, i) - ...
            dt * [implicitOdefun(t(i), x), ...
                implicitOdefun(t(i-1), y(:, i-1))] * implicitCoeff, ...
            y(:, i-1));
    end

    [t, y] = functionOutputParser(t, y, nargout);
end
